DROP DATABASE IF EXISTS AppSchema;
CREATE DATABASE IF NOT EXISTS AppSchema;

USE AppSchema;

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users
(
  user_id INT PRIMARY KEY,
  created_at DATETIME,
  email VARCHAR(255) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS asdf;
CREATE TABLE IF NOT EXISTS asdf
(

);
